function downloadPDF(data) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF("p", "mm", "a4");

  /* ================== THEME ================== */
  const colors = {
    primary: [30, 136, 229],   // Blue
    dark: [33, 33, 33],
    gray: [120, 120, 120],
    light: [245, 247, 250],
    success: [46, 125, 50]
  };

  let y = 20;

  /* ================== HELPERS ================== */
  function centerText(text, size = 16) {
    doc.setFontSize(size);
    doc.text(text, 105, y, { align: "center" });
    y += size / 2 + 4;
  }

  function roundedBox(x, y, w, h, r, color) {
    doc.setFillColor(...color);
    doc.roundedRect(x, y, w, h, r, r, "F");
  }

  function sectionHeader(title) {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    roundedBox(10, y - 8, 190, 12, 4, colors.primary);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(13);
    doc.setFont(undefined, "bold");
    doc.text(title, 14, y);
    doc.setFont(undefined, "normal");
    doc.setTextColor(...colors.dark);
    y += 14;
  }

  function infoRow(label, value) {
    doc.setFontSize(11);
    doc.text(label, 14, y);
    doc.setFont(undefined, "bold");
    doc.text(value, 85, y);
    doc.setFont(undefined, "normal");
    y += 7;
  }

  function divider() {
    doc.setDrawColor(220);
    doc.line(14, y, 196, y);
    y += 6;
  }

  /* ================== LOGO / BRAND ================== */
  doc.setFontSize(20);
  doc.setTextColor(...colors.dark);
  doc.setFont(undefined, "bold");
  doc.text("Coach Abdelmonem", 14, y);

  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.setTextColor(...colors.gray);
  doc.text("Certified Personal Trainer", 14, y + 6);

  doc.setDrawColor(...colors.primary);
  doc.line(14, y + 10, 80, y + 10);

  y += 20;

  /* ================== COVER ================== */
  doc.setTextColor(...colors.primary);
  centerText("PERSONAL TRAINER", 22);
  centerText("NUTRITION PLAN", 22);

  doc.setTextColor(...colors.gray);
  centerText("Personalized • Scientific • Sustainable", 11);

  divider();
  y += 6;

  /* ================== CLIENT SUMMARY ================== */
  sectionHeader("Client Summary");

  infoRow("Name", data.name);
  infoRow("BMI", `${data.bmi} (${data.bmiStatus})`);
  infoRow("Daily Calories", `${data.calories} kcal`);

  divider();

  /* ================== MACROS ================== */
  sectionHeader("Daily Macronutrients");

  infoRow("Protein", `${data.macros.protein} g`);
  infoRow("Fat", `${data.macros.fat} g`);
  infoRow("Carbohydrates", `${data.macros.carbs} g`);

  divider();

  /* ================== MEAL PLAN ================== */
  sectionHeader("7-Day Meal Plan");

  doc.setFontSize(11);

  data.mealPlan.forEach(day => {
    if (y > 245) {
      doc.addPage();
      y = 20;
      sectionHeader("7-Day Meal Plan (cont.)");
    }

    roundedBox(12, y - 4, 186, 36, 5, colors.light);

    doc.setFont(undefined, "bold");
    doc.text(day.day, 16, y);
    doc.setFont(undefined, "normal");
    y += 7;

    doc.text(`Breakfast: ${day.breakfast.name} (${day.breakfast.calories} kcal)`, 18, y);
    y += 6;
    doc.text(`Lunch: ${day.lunch.name} (${day.lunch.calories} kcal)`, 18, y);
    y += 6;
    doc.text(`Dinner: ${day.dinner.name} (${day.dinner.calories} kcal)`, 18, y);
    y += 14;
  });

  /* ================== QUOTE ================== */
  if (y > 230) {
    doc.addPage();
    y = 40;
  }

  roundedBox(25, y, 160, 32, 6, colors.light);

  doc.setFontSize(13);
  doc.setTextColor(...colors.dark);
  doc.text(
    "“Discipline is choosing what you want most over what you want now.”",
    105,
    y + 14,
    { align: "center" }
  );

  doc.setFontSize(11);
  doc.setTextColor(...colors.success);
  doc.text("— Coach Abdelmonem", 160, y + 28);

  /* ================== FOOTER ================== */
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by Mohamed Abdelmonem",
    105,
    292,
    { align: "center" }
  );

  /* ================== SAVE ================== */
  doc.save(`Nutrition-Plan-${data.name}.pdf`);
}
